title: Pizza Paradise
description: "Your ultimate guide to delicious pizza"
baseurl: ""
url: "https://007sriram.github.io"

remote_theme: pages-themes/modernist@v0.2.0
plugins:
  - jekyll-remote-theme
